name: Sync modules and templates to external repos
concurrency:
  group: sync_repos
  cancel-in-progress: true

on:
  workflow_run:
    branches: [main]
    workflows: [Run tests]
    types: [completed]

jobs:
  matrix:
    name: Get job matrix managed in Terraform # in /infra/monorepo.tf
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    outputs:
      modules: ${{ steps.modules.outputs.matrix }}
      templates: ${{ steps.templates.outputs.matrix }}
    steps:
      - name: Get modules matrix
        id: modules
        run: echo "::set-output name=matrix::${{ secrets.modules_matrix }}"
      - name: Get templates matrix
        id: templates
        run: echo "::set-output name=matrix::${{ secrets.templates_matrix }}"

  sync-modules:
    name: Sync ${{ matrix.repo }}
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.matrix.outputs.modules)}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Olivr/copybara-action@main
        with:
          ssh_key: ${{ secrets.copybara_ssh_key }}
          access_token: ${{ secrets.copybara_token }}
          sot_repo: ${{ github.repository_owner }}/oStack
          destination_repo: ${{ github.repository_owner }}/${{ matrix.repo }}
          workflow: push
          push_include: "LICENSE .gitignore .prettierignore .prettierrc.json package.json yarn.lock .config/** modules/.github/** ${{ matrix.path }}/**"
          push_replace: ${{ matrix.replace }}
          push_move: |
            ${{ matrix.path }}||
            modules/.github||.github

  sync-templates:
    name: Sync ${{ matrix.repo }}
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.matrix.outputs.templates)}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Olivr/copybara-action@main
        with:
          ssh_key: ${{ secrets.copybara_ssh_key }}
          access_token: ${{ secrets.copybara_token }}
          sot_repo: ${{ github.repository_owner }}/oStack
          destination_repo: ${{ github.repository_owner }}/${{ matrix.repo }}
          workflow: push
          push_include: "${{ matrix.path }}/**"
          push_move: ${{ matrix.path }}||
